// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp5RzmzTLBp_8JzZnMzeAk1VjjYLtMCLI',
    appId: '1:781566344515:web:f0d7fbea5771721f01c3f6',
    messagingSenderId: '781566344515',
    projectId: 'insta-clone-afb01',
    authDomain: 'insta-clone-afb01.firebaseapp.com',
    storageBucket: 'insta-clone-afb01.appspot.com',
    measurementId: 'G-F3HWZM0KLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4TpVznB9rsR7i4j8uSVTKNXmWJWEybrQ',
    appId: '1:781566344515:android:39ce6b53eb509b6301c3f6',
    messagingSenderId: '781566344515',
    projectId: 'insta-clone-afb01',
    storageBucket: 'insta-clone-afb01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd7cbsz86s9LSR6njwSDqAV9ZCO1EWKB0',
    appId: '1:781566344515:ios:f7bd1349c2fc0f4b01c3f6',
    messagingSenderId: '781566344515',
    projectId: 'insta-clone-afb01',
    storageBucket: 'insta-clone-afb01.appspot.com',
    androidClientId: '781566344515-9tdhq859huhs7b3jjkmj22gn9pij365e.apps.googleusercontent.com',
    iosClientId: '781566344515-2qa26gs6l2k77bmvg447uetr33l04mv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
